// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHvMWYeT_H7ACVLlObPr5ltVyJzK7bGrk',
    appId: '1:875409339667:web:1e1979b13e20416a5516e6',
    messagingSenderId: '875409339667',
    projectId: 'mobileapp6a2a3',
    authDomain: 'mobileapp6a2a3.firebaseapp.com',
    storageBucket: 'mobileapp6a2a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd16fgNTp8sMuaTPNObChyeQnLd8eBcts',
    appId: '1:875409339667:android:b02db8382e68ff575516e6',
    messagingSenderId: '875409339667',
    projectId: 'mobileapp6a2a3',
    storageBucket: 'mobileapp6a2a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnJQBM0hDrILudkMAIMdTUlp8forJ7uJw',
    appId: '1:875409339667:ios:119855d8f5829a175516e6',
    messagingSenderId: '875409339667',
    projectId: 'mobileapp6a2a3',
    storageBucket: 'mobileapp6a2a3.appspot.com',
    iosBundleId: 'com.example.a2v1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnJQBM0hDrILudkMAIMdTUlp8forJ7uJw',
    appId: '1:875409339667:ios:119855d8f5829a175516e6',
    messagingSenderId: '875409339667',
    projectId: 'mobileapp6a2a3',
    storageBucket: 'mobileapp6a2a3.appspot.com',
    iosBundleId: 'com.example.a2v1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHvMWYeT_H7ACVLlObPr5ltVyJzK7bGrk',
    appId: '1:875409339667:web:b3b36608f07689a25516e6',
    messagingSenderId: '875409339667',
    projectId: 'mobileapp6a2a3',
    authDomain: 'mobileapp6a2a3.firebaseapp.com',
    storageBucket: 'mobileapp6a2a3.appspot.com',
  );
}
