// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9CYN20pPajEyt0eMsAsfPd29RinCgJTk',
    appId: '1:107796207892:web:5bb6c7cbacad3f6cdc8a01',
    messagingSenderId: '107796207892',
    projectId: 'mobileapp8a1-cda40',
    authDomain: 'mobileapp8a1-cda40.firebaseapp.com',
    storageBucket: 'mobileapp8a1-cda40.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZhGHibE7DC3kBTc2l8AsF5j8L8ejEE_A',
    appId: '1:107796207892:android:40ecdb5797785531dc8a01',
    messagingSenderId: '107796207892',
    projectId: 'mobileapp8a1-cda40',
    storageBucket: 'mobileapp8a1-cda40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkO6LeQQg0HDXjO0a-vd_ONlRs-rk0KmI',
    appId: '1:107796207892:ios:452dd0404c0261bedc8a01',
    messagingSenderId: '107796207892',
    projectId: 'mobileapp8a1-cda40',
    storageBucket: 'mobileapp8a1-cda40.appspot.com',
    iosBundleId: 'com.example.lec1v1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkO6LeQQg0HDXjO0a-vd_ONlRs-rk0KmI',
    appId: '1:107796207892:ios:452dd0404c0261bedc8a01',
    messagingSenderId: '107796207892',
    projectId: 'mobileapp8a1-cda40',
    storageBucket: 'mobileapp8a1-cda40.appspot.com',
    iosBundleId: 'com.example.lec1v1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9CYN20pPajEyt0eMsAsfPd29RinCgJTk',
    appId: '1:107796207892:web:f0c9275d7800d98adc8a01',
    messagingSenderId: '107796207892',
    projectId: 'mobileapp8a1-cda40',
    authDomain: 'mobileapp8a1-cda40.firebaseapp.com',
    storageBucket: 'mobileapp8a1-cda40.appspot.com',
  );
}
