// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9QgZSrcDIm7WGBKqOuEwcUrjosDx74pk',
    appId: '1:818059438162:web:12e94f1864eb0260ffd78b',
    messagingSenderId: '818059438162',
    projectId: 'mobileapp6a1a3',
    authDomain: 'mobileapp6a1a3.firebaseapp.com',
    storageBucket: 'mobileapp6a1a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJzIal-l3_IB55Xb9VFgYrFMxAaP6iY9c',
    appId: '1:818059438162:android:65c8b77c0dcc6455ffd78b',
    messagingSenderId: '818059438162',
    projectId: 'mobileapp6a1a3',
    storageBucket: 'mobileapp6a1a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_rvLTTBI6DS2DFcGyV6AJC8VTprAGf9Q',
    appId: '1:818059438162:ios:ff58ca04f57e80aeffd78b',
    messagingSenderId: '818059438162',
    projectId: 'mobileapp6a1a3',
    storageBucket: 'mobileapp6a1a3.appspot.com',
    iosBundleId: 'com.example.sourcev1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_rvLTTBI6DS2DFcGyV6AJC8VTprAGf9Q',
    appId: '1:818059438162:ios:ff58ca04f57e80aeffd78b',
    messagingSenderId: '818059438162',
    projectId: 'mobileapp6a1a3',
    storageBucket: 'mobileapp6a1a3.appspot.com',
    iosBundleId: 'com.example.sourcev1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9QgZSrcDIm7WGBKqOuEwcUrjosDx74pk',
    appId: '1:818059438162:web:19538ffd3e93f311ffd78b',
    messagingSenderId: '818059438162',
    projectId: 'mobileapp6a1a3',
    authDomain: 'mobileapp6a1a3.firebaseapp.com',
    storageBucket: 'mobileapp6a1a3.appspot.com',
  );
}
